version: '3.3'

services:
  nginx:
    container_name: nginx-wordpress
    image: nginx:latest
    ports:
      - '80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    # restart: always
    networks:
      - nginxproxy_default

  db:
    image: mysql:5.7
    ports: 
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql
    # restart: always
    environment:
      # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      # MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_PASSWORD: root
    networks:
      - nginxproxy_default
    secrets:
      - db_root_password
      - db_password

  wordpress:
    container_name: wp
    image: wordpress:fpm-alpine
    ports:
      - '9000'
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wpprefix_
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      # WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_PASSWORD: root
    depends_on:
      - db
    # restart: always
    networks:
      - nginxproxy_default
    secrets:
      - db_password
    
# volumes:
  # db_data:
  # wp_content:
  # nginx_wp_logs:

secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt

networks:
  nginxproxy_default:
    external: true